"""Event & Welcome Screen Sponsor Logos

Revision ID: 1168569d9d87
Revises: 2c29f67dc787
Create Date: 2014-05-04 05:15:40.870787

"""

# revision identifiers, used by Alembic.
revision = '1168569d9d87'
down_revision = '2c29f67dc787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_logo', sa.Unicode(length=120), nullable=True))
    op.add_column('event', sa.Column('welcome_logo', sa.Unicode(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'welcome_logo')
    op.drop_column('event', 'event_logo')
    ### end Alembic commands ###
