"""kiosk new fields

Revision ID: 19ae3b2b3139
Revises: 46b28d849889
Create Date: 2013-06-07 16:50:34.747749

"""

# revision identifiers, used by Alembic.
revision = '19ae3b2b3139'
down_revision = '46b28d849889'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosk', sa.Column('company_logo', sa.Unicode(length=120), nullable=True))
    op.add_column('kiosk', sa.Column('company_tag', sa.Unicode(length=150), nullable=True))
    op.add_column('kiosk', sa.Column('tap_msg', sa.Unicode(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosk', 'tap_msg')
    op.drop_column('kiosk', 'company_tag')
    op.drop_column('kiosk', 'company_logo')
    ### end Alembic commands ###
