"""Participant email field unique

Revision ID: 1af250f5ec7c
Revises: 49ea5d63f054
Create Date: 2013-07-10 06:33:41.507172

"""

# revision identifiers, used by Alembic.
revision = '1af250f5ec7c'
down_revision = '49ea5d63f054'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
