"""Contact Exchange Logs

Revision ID: 1dabb6683d93
Revises: 19ae3b2b3139
Create Date: 2013-06-27 23:42:24.631704

"""

# revision identifiers, used by Alembic.
revision = '1dabb6683d93'
down_revision = '19ae3b2b3139'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cxlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('users', sa.Unicode(length=200), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('log_message', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cxlog')
    ### end Alembic commands ###
