"""Participant nfc_id nullable

Revision ID: 25f2da5ce7b3
Revises: 3b3d975b97b0
Create Date: 2013-07-08 21:40:40.204175

"""

# revision identifiers, used by Alembic.
revision = '25f2da5ce7b3'
down_revision = '3b3d975b97b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
