"""On the spot tickets

Revision ID: 2838755f07a2
Revises: 47dddf6f5e5
Create Date: 2014-07-23 05:08:17.276374

"""

# revision identifiers, used by Alembic.
revision = '2838755f07a2'
down_revision = '47dddf6f5e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('on_the_spot', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('ticket', 'on_the_spot', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'on_the_spot')
    ### end Alembic commands ###
