"""Venue, Activity from_funnel

Revision ID: 28dea4ec9f96
Revises: 41082ae76331
Create Date: 2014-02-10 08:05:40.191683

"""

# revision identifiers, used by Alembic.
revision = '28dea4ec9f96'
down_revision = '41082ae76331'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('from_funnel', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('activity', 'from_funnel', server_default=None)
    op.add_column('venue', sa.Column('from_funnel', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('venue', 'from_funnel', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'from_funnel')
    op.drop_column('activity', 'from_funnel')
    ### end Alembic commands ###
