"""Participant additional notes

Revision ID: 2a3f8c4f02a2
Revises: 1af250f5ec7c
Create Date: 2013-07-10 16:46:55.322546

"""

# revision identifiers, used by Alembic.
revision = '2a3f8c4f02a2'
down_revision = '1af250f5ec7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('notes', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'notes')
    ### end Alembic commands ###
