"""Participant.image

Revision ID: 2c29f67dc787
Revises: 45e375225809
Create Date: 2014-02-13 06:25:47.708530

"""

# revision identifiers, used by Alembic.
revision = '2c29f67dc787'
down_revision = '45e375225809'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('image', sa.Text(), server_default="LOAD", nullable=True))
    op.alter_column('participant', 'image', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'image')
    ### end Alembic commands ###
