"""Events From and To Dates

Revision ID: 2f53c273dac
Revises: 1dabb6683d93
Create Date: 2013-07-03 08:39:06.974139

"""

# revision identifiers, used by Alembic.
revision = '2f53c273dac'
down_revision = '1dabb6683d93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('from_date', sa.Date(), nullable=True))
    op.add_column('event', sa.Column('to_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'to_date')
    op.drop_column('event', 'from_date')
    ### end Alembic commands ###
