"""Event.eventframe_url

Revision ID: 31c5228c75bb
Revises: 28e66d8c063f
Create Date: 2014-02-11 08:16:45.866374

"""

# revision identifiers, used by Alembic.
revision = '31c5228c75bb'
down_revision = '28e66d8c063f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('eventframe_sync', sa.Unicode(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'eventframe_sync')
    ### end Alembic commands ###
