"""Checkin Email

Revision ID: 3987dc471c3
Revises: 1168569d9d87
Create Date: 2014-05-14 23:51:33.781550

"""

# revision identifiers, used by Alembic.
revision = '3987dc471c3'
down_revision = '1168569d9d87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_checkins', sa.Column('email', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('activity_checkins', 'email', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_checkins', 'email')
    ### end Alembic commands ###
