"""Participant Columns Changed

Revision ID: 3b3d975b97b0
Revises: 4d264f13c323
Create Date: 2013-07-08 21:19:51.323886

"""

# revision identifiers, used by Alembic.
revision = '3b3d975b97b0'
down_revision = '4d264f13c323'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('purchases', sa.Unicode(length=200), nullable=True))
    op.add_column('participant', sa.Column('purchased_tee', sa.Boolean(), nullable=True))
    op.add_column('participant', sa.Column('phone', sa.Unicode(length=15), nullable=True))
    op.drop_column('participant', u'ticket_type')
    op.drop_column('participant', u'tshirt_size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column(u'tshirt_size', sa.INTEGER(), nullable=False))
    op.add_column('participant', sa.Column(u'ticket_type', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('participant', 'phone')
    op.drop_column('participant', 'purchased_tee')
    op.drop_column('participant', 'purchases')
    ### end Alembic commands ###
