"""Other Event Badge Printing options

Revision ID: 41bca295591d
Revises: 12ad11a99786
Create Date: 2014-02-09 04:54:42.816242

"""

# revision identifiers, used by Alembic.
revision = '41bca295591d'
down_revision = '12ad11a99786'

from alembic import op
import sqlalchemy as sa
from coaster.sqlalchemy import JsonDict


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('speaker_options', JsonDict, server_default='{}', nullable=False))
    op.alter_column('event', 'speaker_options', server_default=None)
    op.add_column('event', sa.Column('crew_options', JsonDict, server_default='{}', nullable=False))
    op.alter_column('event', 'crew_options', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
