"""Participant.collected_tee

Revision ID: 4296777663b9
Revises: 30be99b7ae7
Create Date: 2013-11-27 18:48:07.247243

"""

# revision identifiers, used by Alembic.
revision = '4296777663b9'
down_revision = '30be99b7ae7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('collected_tee', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'collected_tee')
    ### end Alembic commands ###
