"""TicketNumberUnique

Revision ID: 45e375225809
Revises: 31c5228c75bb
Create Date: 2014-02-11 10:56:17.709384

"""

# revision identifiers, used by Alembic.
revision = '45e375225809'
down_revision = '31c5228c75bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participant_ticket_number_key', 'participant')
    op.create_unique_constraint('participant_event_id_ticket_number_key', 'participant', ['event_id', 'ticket_number'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participant_event_id_ticket_number_key', 'participant')
    op.create_unique_constraint('participant_ticket_number_key', 'participant', ['ticket_number'])
    ### end Alembic commands ###
