"""Activity

Revision ID: 4973d39adcb6
Revises: ce1961f729a
Create Date: 2014-02-10 02:43:43.033795

"""

# revision identifiers, used by Alembic.
revision = '4973d39adcb6'
down_revision = 'ce1961f729a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Unicode(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'venue', u'subtitle')
    op.alter_column(u'venue', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'venue', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column(u'venue', sa.Column(u'subtitle', sa.VARCHAR(length=80), nullable=True))
    op.drop_table('activity')
    ### end Alembic commands ###
