"""Participant online_reg field

Revision ID: 49ea5d63f054
Revises: 25f2da5ce7b3
Create Date: 2013-07-08 22:00:35.006536

"""

# revision identifiers, used by Alembic.
revision = '49ea5d63f054'
down_revision = '25f2da5ce7b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('online_reg', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'online_reg')
    ### end Alembic commands ###
