"""Removed nfc_id column

Revision ID: 4cdaf9d17f49
Revises: 54f5351fbf9e
Create Date: 2013-07-24 00:18:53.214415

"""

# revision identifiers, used by Alembic.
revision = '4cdaf9d17f49'
down_revision = '54f5351fbf9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', u'nfc_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column(u'nfc_id', sa.VARCHAR(length=80), nullable=True))
    ### end Alembic commands ###
