"""Doattend event ID

Revision ID: 4d264f13c323
Revises: 5361cebc7a82
Create Date: 2013-07-03 22:53:55.792357

"""

# revision identifiers, used by Alembic.
revision = '4d264f13c323'
down_revision = '5361cebc7a82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('doattend_id', sa.Unicode(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'doattend_id')
    ### end Alembic commands ###
