"""Unique constraint is now on nfc_id+event

Revision ID: 4d30ec36e917
Revises: a48e1f6838c
Create Date: 2013-07-24 00:22:01.199548

"""

# revision identifiers, used by Alembic.
revision = '4d30ec36e917'
down_revision = 'a48e1f6838c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_participant_nfc_id", "participant", ["event_id", "nfc_id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_participant_nfc_id", "participant")
    ### end Alembic commands ###
