"""Events date column nullable

Revision ID: 5361cebc7a82
Revises: 2f53c273dac
Create Date: 2013-07-03 08:40:59.525165

"""

# revision identifiers, used by Alembic.
revision = '5361cebc7a82'
down_revision = '2f53c273dac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', u'date',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', u'date',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###
