"""Kiosk Privacy Policy field

Revision ID: 54f5351fbf9e
Revises: 3ab7d945cb73
Create Date: 2013-07-11 23:45:53.182565

"""

# revision identifiers, used by Alembic.
revision = '54f5351fbf9e'
down_revision = '3ab7d945cb73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosk', sa.Column('privacy_policy', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosk', 'privacy_policy')
    ### end Alembic commands ###
