"""Event badges

Revision ID: 5a2784d6249f
Revises: 30be99b7ae7
Create Date: 2014-02-09 01:29:53.229739

"""

# revision identifiers, used by Alembic.
revision = '5a2784d6249f'
down_revision = '30be99b7ae7'

from alembic import op
import sqlalchemy as sa
from coaster.sqlalchemy import JsonDict

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('options', JsonDict, server_default='{}', nullable=False))
    op.alter_column('event', 'options', server_default=None)
    op.add_column('event', sa.Column('print_type', sa.Unicode(length=10), server_default=u'badge', nullable=False))
    op.alter_column('event', 'print_type', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'print_type')
    op.drop_column('event', 'options')
    ### end Alembic commands ###
