"""Reintroduced nfc_id column

Revision ID: a48e1f6838c
Revises: 4cdaf9d17f49
Create Date: 2013-07-24 00:19:56.136286

"""

# revision identifiers, used by Alembic.
revision = 'a48e1f6838c'
down_revision = '4cdaf9d17f49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('nfc_id', sa.Unicode(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'nfc_id')
    ### end Alembic commands ###
