"""Venues

Revision ID: ce1961f729a
Revises: 1a5ec9ee2990
Create Date: 2014-02-09 09:03:12.858645

"""

# revision identifiers, used by Alembic.
revision = 'ce1961f729a'
down_revision = '1a5ec9ee2990'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Unicode(length=80), nullable=False),
    sa.Column('subtitle', sa.Unicode(length=80), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'event', u'venue')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'event', sa.Column(u'venue', sa.VARCHAR(length=80), nullable=False))
    op.drop_table('venue')
    ### end Alembic commands ###
